name: "Example OIDC"
on:
  push:
    branches:
      - "main"

env:
  # ADD YOUR OWN BUCKET NAME HERE
  BUCKET_NAME: github-example-wif

jobs:
  run:
    name: "List bucket contents"
    permissions:
      id-token: write
      contents: read
    runs-on: "ubuntu-latest"
    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{ secrets.PROVIDER_NAME }}
          service_account: ${{ secrets.SA_EMAIL }}

      - id: "list-bucket-contents"
        run: |-
          curl -sSf https://storage.googleapis.com/storage/v1/b/$BUCKET_NAME/o \
            --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}"
